version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  el1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: el1
    environment:
      - node.name=el1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=el2
      - cluster.initial_master_nodes=el1,el2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  el2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: el2
    environment:
      - node.name=el2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=el1
      - cluster.initial_master_nodes=el1,el2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic
volumes:
  data01:
    driver: local
  data02:
      driver: local

networks:
  elastic:
    driver: bridge